version: '3.7'

services:
  mariadb:
    image: '8ctopus/mariadb:latest'
    container_name: dev-db
    ports:
      - 3306:3306
    entrypoint: >
      sh -c "rc-service mariadb restart &&
             mysql < /init.sql &&
             tail -f /dev/null"
  web:
    image: 8ctopus/web:latest
    container_name: dev-web
    ports:
      - 8000:80
    links:
      - mariadb
    restart: always
    volumes:
      # development directory
      - ./dev/:/var/www/site/
      # expose apache logs to host
      - ./log/:/var/log/apache2/
    entrypoint: httpd -X
