version: '3.7'

services:
  mariadb:
    image: 8ct8pus/mariadb-alpine:latest
    container_name: dev-db
    ports:
      - 3306:3306
    volumes:
      # expose mariadb config to host
      - ./etc/:/docker/etc/
  web:
    image: 8ct8pus/apache-php-alpine:latest
    container_name: dev-web
    ports:
      - 8000:80
    links:
      - mariadb
    volumes:
      # development directory
      - ./dev/:/var/www/site/
      # expose apache logs to host
      - ./log/:/var/log/apache2/
      # expose apache2 and php config to host
      - ./etc/:/docker/etc/
