version: '3.7'

services:
  mariadb:
    image: 8ct8pus/mariadb-alpine:1.0.8
    container_name: sandbox-db
    ports:
      - 3306:3306
    volumes:
      # expose mariadb config to host
      - ./docker/etc/:/docker/etc/
      # save mariadb databases to named volume
      - database:/var/lib/mysql/
  web:
    # php 8.2.0 RC6 with virtual hosts
    image: 8ct8pus/apache-php-fpm-alpine:2.0.2
    # php 8.2.0 RC6
    #image: 8ct8pus/apache-php-fpm-alpine:1.4.4
    # php 8.1.7
    #image: 8ct8pus/apache-php-fpm-alpine:1.3.6
    # php 8.0.17
    #image: 8ct8pus/apache-php-fpm-alpine:1.2.8
    # php 7.4.21
    #image: 8ct8pus/apache-php-fpm-alpine:1.1.3
    hostname: sandbox
    container_name: sandbox
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=localhost
      - DOCUMENT_ROOT=/public
    links:
      - mariadb
    volumes:
      # development directory
      - ./sites/:/sites/
      # expose apache2 and php config to host
      - ./docker/etc/:/docker/etc/
volumes:
  database:
