version: '3.7'

services:
  mariadb:
    image: 8ct8pus/mariadb-alpine:latest
    container_name: sandbox-db
    ports:
      - 3306:3306
    volumes:
      # expose mariadb config to host
      - ./etc/:/docker/etc/
      # save mariadb databases to named volume
      - database:/var/lib/mysql/
  web:
    image: 8ct8pus/apache-php-fpm-alpine:1.0.9
    container_name: sandbox
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=localhost
      - DOCUMENT_ROOT=/public
    links:
      - mariadb
    volumes:
      # development directory
      - ./src/:/var/www/html/
      # expose apache logs to host
      - ./log/:/var/log/apache2/
      # expose apache2 and php config to host
      - ./etc/:/docker/etc/
      # expose ssl certificates to host
      - ./ssl/:/etc/ssl/apache2/
volumes:
  database:
